apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: ns-api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: alexandrebunn/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
            name: api-configmap
        env:
        - name: Mongo__User
          valueFrom: 
            configMapRef:
              key: MONGO_INITDB_ROOT_USERNAME
              value: mongodb-configmap
        - name: Mongo__Password
          valueFrom: 
            configMapRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              value: mongodb-configmap

        