apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ns-api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: 30000
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  type: NodePort